package com.tc.execution.enums;

public enum PROPERTY_KEYS {
    CALLING_PROFILE_ID,
    EMAIL_RECEIVER,
    SEND_MAILS,
    EMAIL_HOST,
    EMAIL_PORT,
    EMAIL_SENDER,
    EMAIL_USER,
    EMAIL_PASS,
    EMAIL_SUBJECT,
    EMAIL_DELIVERY_SUBJECT,
    EMAIL_DELIVERY_HEADER,
    EMAIL_HEADER,
    EMAIL_BODY,
    SYNC_NUMBER_SETTINGS,
    SYNC_CONSENTS,
    RUN_SIP_TESTS,
    POLL_SIP_TESTS,
    EMAIL_SEND_TO_CUSTOMER,
    EMAIL_SEND_TO_DELIVERY,
    SEND_BILLING_INFO_SE,
    SEND_BILLING_INFO_NO,
    SEND_BILLING_INFO_FI,
    BILLING_REPORT_RECEIVER_SE,
    BILLING_REPORT_RECEIVER_NO,
    BILLING_REPORT_RECEIVER_FI

}
